name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test (${{ matrix.integration.name }})
    runs-on: ${{ matrix.integration.os }}-latest
    env:
      MISE_PROFILE: cicd
    strategy:
      fail-fast: false
      matrix:
        integration:
          - name: Fixtures
            os: ubuntu
            target: ./test
            setup_scripts: []
            secrets: []
          - name: SSH
            os: ubuntu
            target: ./...
            setup_scripts:
              - .github/scripts/setup/ssh.sh
            secrets: [GHA_DEPLOY_KEY]
          - name: SOPS
            os: ubuntu
            target: ./...
            setup_scripts:
              - .github/scripts/setup/sops.sh
            secrets: []
          - name: Tflint
            os: ubuntu
            target: ./...
            setup_scripts:
              - .github/scripts/setup/tflint.sh
            secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
          - name: GCP
            os: ubuntu
            target: ./...
            setup_scripts:
              - .github/scripts/setup/gcp.sh
            secrets: [GCLOUD_SERVICE_KEY, GOOGLE_CLOUD_PROJECT, GOOGLE_COMPUTE_ZONE, GOOGLE_IDENTITY_EMAIL, GOOGLE_PROJECT_ID]
          - name: AWS
            os: ubuntu
            target: ./...
            setup_scripts:
              - .github/scripts/setup/aws.sh
            secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
          - name: AWSGCP
            os: ubuntu
            target: ./...
            setup_scripts:
              - .github/scripts/setup/aws.sh
              - .github/scripts/setup/gcp.sh
            secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, GCLOUD_SERVICE_KEY, GOOGLE_CLOUD_PROJECT, GOOGLE_COMPUTE_ZONE, GOOGLE_IDENTITY_EMAIL, GOOGLE_PROJECT_ID]
          - name: Engine
            os: ubuntu
            target: ./...
            setup_scripts:
              - .github/scripts/setup/engine.sh
            secrets: []

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Secrets Environment
        if: ${{ matrix.integration.requires_setup }}
        id: generate-secrets
        run: |
          ENV_FILE="${GITHUB_WORKSPACE}/.env.secrets"
          echo "export SCRIPT_PATHS='${{ matrix.integration.setup_scripts }}'" > $ENV_FILE
          
          # Loop through secrets dynamically and export them to the file
          for SECRET in ${{ join(matrix.integration.secrets, ' ') }}; do
            SECRET_VALUE_NAME="secrets.${SECRET}"
            SECRET_VALUE="${{ env[SECRET_VALUE_NAME] }}"
            if [[ -n "$SECRET_VALUE" ]]; then
              printf "export %s='%s'\n" "$SECRET" "$SECRET_VALUE" >> $ENV_FILE
            fi
          done

          echo "Created environment file with secrets for ${{ matrix.integration.name }}"
        shell: bash

      - name: Setup
        if: ${{ matrix.integration.requires_setup }}
        run: |
          # Source the environment file
          source "${GITHUB_WORKSPACE}/.env.secrets"
          
          # Loop through setup scripts and execute them
          for SCRIPT in ${{ matrix.integration.setup_scripts }}; do
            if [[ -n "$SCRIPT" ]]; then
              chmod +x "$SCRIPT"
              "$SCRIPT"
            fi
          done
        shell: bash

      - name: Use mise to install dependencies
        uses: jdx/mise-action@v2
        with:
          version: 2025.4.4
          experimental: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: go-cache-paths
        run: |
          echo "go-build=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Go Build Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-integration-test-${{ matrix.integration.name }}-${{ hashFiles('**/go.sum') }}

      - name: Run Tests
        run: |
          go test -v ${TAGS:+-tags "$TAGS"} ${RUN:+-run "$RUN"} "${TARGET}"
        shell: bash
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET: ${{ matrix.integration.target }}
          TAGS: ${{ matrix.integration.tags }}
          RUN: ${{ matrix.integration.run }}
