name: Pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  precommit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Append python to mise.toml
        run: |
          echo "pre-commit = \"4.2.0\"" >> mise.toml

      - name: Create default packages file
        run: |
          # Unlike the Python one below, this one can't be at
          # a configurable location, so we always write it to the home dir.
          cat <<EOF > ~/.default-go-packages
          golang.org/x/tools/cmd/goimports@latest
          EOF

          echo "$HOME/go/bin" >> "$GITHUB_PATH"

      - name: Use mise to install dependencies
        uses: jdx/mise-action@v2
        with:
          version: 2025.4.4
        env:
          # Adding token here to reduce the likelihood of hitting rate limit issues.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: go-cache-paths
        run: |
          echo "go-build=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"

      - name: Go Build Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}-${{ matrix.os }}-${{ matrix.arch }}

      - name: Run pre-commit hooks
        env:
          GOPROXY: direct
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          pre-commit install
          pre-commit run --all-files
